/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ardab
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        MenuPaket = new javax.swing.JLabel();
        MenuKurir = new javax.swing.JLabel();
        MenuPengiriman = new javax.swing.JLabel();
        plhPaket = new javax.swing.JLabel();
        plhKirim = new javax.swing.JLabel();
        plhExit = new javax.swing.JLabel();
        MenuExit = new javax.swing.JLabel();
        plhKurir = new javax.swing.JLabel();
        MenuLacak = new javax.swing.JLabel();
        plhLacak = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DASHBOARD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        MenuPaket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Asset/PaketCom.png"))); // NOI18N
        MenuPaket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPaketMouseClicked(evt);
            }
        });

        MenuKurir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Asset/KurirCom.png"))); // NOI18N
        MenuKurir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuKurir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuKurirMouseClicked(evt);
            }
        });

        MenuPengiriman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Asset/DeliveryCom.png"))); // NOI18N
        MenuPengiriman.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuPengiriman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPengirimanMouseClicked(evt);
            }
        });

        plhPaket.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        plhPaket.setForeground(new java.awt.Color(255, 255, 255));
        plhPaket.setText("Paket");
        plhPaket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plhPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plhPaketMouseClicked(evt);
            }
        });

        plhKirim.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        plhKirim.setForeground(new java.awt.Color(255, 255, 255));
        plhKirim.setText("Pengiriman");
        plhKirim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plhKirim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plhKirimMouseClicked(evt);
            }
        });

        plhExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        plhExit.setForeground(new java.awt.Color(255, 255, 255));
        plhExit.setText("Keluar");
        plhExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plhExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plhExitMouseClicked(evt);
            }
        });

        MenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Asset/ExitCom2.png"))); // NOI18N
        MenuExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuExitMouseClicked(evt);
            }
        });

        plhKurir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        plhKurir.setForeground(new java.awt.Color(255, 255, 255));
        plhKurir.setText("Kurir");
        plhKurir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plhKurir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plhKurirMouseClicked(evt);
            }
        });

        MenuLacak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Asset/LacakCom.png"))); // NOI18N
        MenuLacak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuLacak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuLacakMouseClicked(evt);
            }
        });

        plhLacak.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        plhLacak.setForeground(new java.awt.Color(255, 255, 255));
        plhLacak.setText("Lacak Paket");
        plhLacak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plhLacak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plhLacakMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(plhPaket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(plhKurir)
                .addGap(184, 184, 184)
                .addComponent(plhKirim)
                .addGap(94, 94, 94))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(MenuPaket)
                        .addGap(117, 117, 117)
                        .addComponent(MenuKurir)
                        .addGap(123, 123, 123)
                        .addComponent(MenuPengiriman))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addComponent(MenuExit))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(plhExit)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(MenuLacak))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(plhLacak)))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuKurir)
                    .addComponent(MenuPaket)
                    .addComponent(MenuPengiriman))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plhPaket)
                    .addComponent(plhKirim)
                    .addComponent(plhKurir))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuExit)
                    .addComponent(MenuLacak))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plhExit)
                    .addComponent(plhLacak))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuPaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPaketMouseClicked
        this.dispose();
        FormPacket pkt = new FormPacket();
        pkt.setVisible(true);
    }//GEN-LAST:event_MenuPaketMouseClicked

    private void MenuKurirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuKurirMouseClicked
        this.dispose();
        FormCourier krr = new FormCourier();
        krr.setVisible(true);
    }//GEN-LAST:event_MenuKurirMouseClicked

    private void MenuPengirimanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPengirimanMouseClicked
        this.dispose();
        FormDelivery pengiriman = new FormDelivery();
        pengiriman.setVisible(true);
    }//GEN-LAST:event_MenuPengirimanMouseClicked

    private void plhPaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plhPaketMouseClicked
        this.dispose();
        FormPacket pkt = new FormPacket();
        pkt.setVisible(true);
    }//GEN-LAST:event_plhPaketMouseClicked

    private void plhExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plhExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_plhExitMouseClicked

    private void plhKirimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plhKirimMouseClicked
        this.dispose();
        FormDelivery pengiriman = new FormDelivery();
        pengiriman.setVisible(true);
    }//GEN-LAST:event_plhKirimMouseClicked

    private void MenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_MenuExitMouseClicked

    private void plhKurirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plhKurirMouseClicked
        this.dispose();
        FormCourier krr = new FormCourier();
        krr.setVisible(true);
    }//GEN-LAST:event_plhKurirMouseClicked

    private void MenuLacakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLacakMouseClicked
        this.dispose();
        Lacak lck = new Lacak();
        lck.setVisible(true);
    }//GEN-LAST:event_MenuLacakMouseClicked

    private void plhLacakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plhLacakMouseClicked
        this.dispose();
        Lacak lck = new Lacak();
        lck.setVisible(true);
    }//GEN-LAST:event_plhLacakMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuExit;
    private javax.swing.JLabel MenuKurir;
    private javax.swing.JLabel MenuLacak;
    private javax.swing.JLabel MenuPaket;
    private javax.swing.JLabel MenuPengiriman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel plhExit;
    private javax.swing.JLabel plhKirim;
    private javax.swing.JLabel plhKurir;
    private javax.swing.JLabel plhLacak;
    private javax.swing.JLabel plhPaket;
    // End of variables declaration//GEN-END:variables
}
